spring:
  application:
    name: sleuthdemo

logging:
  level:
#    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
