spring:
  datasource:
    url: jdbc:mysql://localhost/diandu_cms?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.swordess.somekotlin.mybatis.model

logging:
  level:
    org.swordess.somekotlin.mybatis.mapper: DEBUG
